import Header from "@/components/ui/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./providers";
import NavBar from "@/components/navBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Determinar a franquia com base na URL sem recriar o header

  return (
    <html lang="pt-Br">
      <body>
        <ContextProvider>
          <div>
            <NavBar />

            {children}
          </div>
        </ContextProvider>
      </body>
    </html>
  );
}
